## Linear Algebra Review + How to do it in Python

In [18]:
## This is how we import modules
from IPython.display import Math, Latex  # for writing latex code in jupyter

#### Vectors and Matrices

You have seen in lectures that it is useful to represent many quantities as vectors or matrices. For example you could describe a person as person(age, height, education) as a vector with different features representing dimensions. Similary, a collection of persons can be represented as stack of vectors ==> i.e., a matrix.

In [13]:
# %%latex
from IPython.display import Math,Latex
Latex(r'''
\begin{align*}
&u = \begin{bmatrix}x_1\\ x_2\end{bmatrix}, \quad\quad v = \begin{bmatrix}y_1\\ y_2\end{bmatrix}\\
&\text{Length:} = \lvert\lvert u \rvert\rvert = \sqrt{x_1^2 + x_2^2} \\
&u + v = \begin{bmatrix}x_1 + y_1\\ x_2 + y_2\end{bmatrix}
\end{align*}


''')


<IPython.core.display.Latex object>

In [10]:
Latex(r'''
\begin{align*}
\text{Consider matrix } &X \in \mathbb{R}^{m\times n} \text{ given as:}\\
X &= \begin{bmatrix}
    x_{11}       & x_{12} & x_{13} & \dots & x_{1n} \\
    x_{21}       & x_{22} & x_{23} & \dots & x_{2n} \\
    \dots \\
    x_{m1}       & x_{m2} & x_{m3} & \dots & x_{mn}
\end{bmatrix}, 
Y = \begin{bmatrix}
    y_{11}       & y_{12} & y_{13} & \dots & y_{1n} \\
    y_{21}       & y_{22} & y_{23} & \dots & y_{2n} \\
    \dots \\
    y_{m1}       & y_{m2} & y_{m3} & \dots & y_{mn}
\end{bmatrix}\\\\

\text{Sum:}\quad &Z = X + Y; \quad z_{ij} = x_{ij} + y_{ij}
\end{align*}
''')


<IPython.core.display.Latex object>

#### Matrices and Vectors (in Python)

NUMPY: A supremely-optimized, well-maintained scientific computing package for Python. I’m still learning new things about it. I 'm sure you'll appreciate its prowess as you learn more.

In [19]:
import numpy as np # conventional alias

In [20]:
X = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
u = np.array([[1],
 [2],
 [3]])

In [21]:
## matrix
print(X)
print("shape:", X.shape) 
print("dim (axes):", X.ndim) 
print("type of elements:", X.dtype.name) 
print("size of elements:", X.itemsize) 
print("size:", X.size) 
print("type:", type(X)) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
dim (axes): 2
type of elements: int64
size of elements: 8
size: 9
type: <class 'numpy.ndarray'>


In [22]:
## vector
print(u)
print("shape:", u.shape) 
print("dim (axes):", u.ndim) 
print("type of elements:", u.dtype.name) 
print("size of elements:", u.itemsize) 
print("size:", u.size) 
print("type:", type(u)) 

[[1]
 [2]
 [3]]
shape: (3, 1)
dim (axes): 2
type of elements: int64
size of elements: 8
size: 3
type: <class 'numpy.ndarray'>


In [23]:
u_single_dim = np.array([1, 2, 3])
u_single_dim.shape

(3,)

In [24]:
## Indexing
X[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [25]:
## Dot (or Inner) product
Latex(r'''
\begin{align*}
u.v = x_{1} y_{1} + x_{2} y_{2}
\end{align*}
''')

<IPython.core.display.Latex object>

In [26]:
## Outer product
Latex(r'''
\begin{align*}
u \otimes v = u.v^T = \begin{bmatrix}x_1\\x_2\end{bmatrix}. \begin{bmatrix}y_1 \quad y_2\end{bmatrix}
=\begin{bmatrix} x_1 y_1 \quad x_1 y_2\\ x_2 y_1 \quad x_2 y_2\end{bmatrix}
\end{align*}
'''
)

<IPython.core.display.Latex object>

#### Matrix multiplication
Matrix product is obtained by dot product between rows of first matrix and columns of second matrix. This is illustrated in the figure below.
<figure>
  <center>
  <img src="fig/matmul.png" width="700" height="200">
  </center>
</figure>

In [27]:
## Let us define a matrix Y
Y = np.arange(15, dtype = float).reshape(3, 5)

In [28]:
print('Multiplied matrix:')
print(np.matmul(X, Y)) # matrix multiplication of X and Y
print(np.dot(X, Y)) ## same as matmul for 2-d matrices

Multiplied matrix:
[[ 40.  46.  52.  58.  64.]
 [ 85. 100. 115. 130. 145.]
 [130. 154. 178. 202. 226.]]
[[ 40.  46.  52.  58.  64.]
 [ 85. 100. 115. 130. 145.]
 [130. 154. 178. 202. 226.]]


In [30]:
## Dot product between a matrix and a vector
print(np.dot(X, u))
## Element wise operation
print(np.multiply(X, u))
print(X * u)

[[14]
 [32]
 [50]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [31]:
### Transpose
print(X.T) # transpose a matrix
print()
print(u.T) # transpose a vector

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 2 3]]


In [32]:
## Special ways to create matrices
print( np.arange(15, dtype = float).reshape(3, 5))
print( "\n---")

print( np.zeros((3,4))) # all zeroes
print( "\n---")

print( np.ones((1,2,3,4))) # all ones
print( "\n---")

print( np.empty((1,3), dtype = str)) # empty
print( "\n---")

print(np.eye(3))  # identity matrix of dimension 3

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

---
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

---
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]

---
[['' '' '']]

---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
### Difference between arange and linspace

print("arange:", np.arange(0, 2, 0.25)) # Exclusive upper bound, provide step

print("\n--")

print("lin Space:", np.linspace(0, 2, 10)) # (Can look like) inclusive upper bound, but not really, provide length


arange: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75]

--
lin Space: [0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [34]:
### Element-wise operations

a = np.array( [20, 30, 40, 50] )
b = np.arange( 4 )

print(a-b)                  # Addition/Subtration 

print(b**2)                 # Exponentiation

print(10*np.sin(a))         # Multiplication (!)

print(a < 35)               # Boolean

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
